name: DualPRE
channels:
  - conda-forge
  - bioconda
  - defaults
  - pytorch
dependencies:
  - python=3.8.16
  - lifelines=0.27.8
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - scipy=1.10.1